name: Get Citation Data

on:
  page_build:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install -r google_scholar_crawler/requirements.txt
        python -m pip check
    - name: Fetch citation data
      working-directory: google_scholar_crawler
      run: python main.py
      env:
        GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
    - name: Publish citation data
      working-directory: google_scholar_crawler/results
      run: |
        git init
        git config --local user.name "${GITHUB_ACTOR}"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        git add *.json
        git commit -m "Updated Citation Data"
        git push "${remote_repo}" HEAD:google-scholar-stats --force
